# Generated by Django 2.1.7 on 2019-03-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190328_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '用户留言信息', 'verbose_name_plural': '用户留言信息'},
        ),
        migrations.AlterModelTable(
            name='usermessage',
            table='user_message',
        ),
    ]
